// AUTO-GENERATED FILE -- DO NOT EDIT
// Generated by scripts/generate-jsx.js

declare global {
  interface HTMLElementTagNameMap {
    "ef-alert": EfAlert;
    "ef-badge": EfBadge;
    "ef-button": EfButton;
    "ef-icon": EfIcon;
    "ef-status": EfStatus;
  }
}

export {};
