// AUTO-GENERATED FILE -- DO NOT EDIT
// Generated by scripts/generate-jsx.js

declare namespace JSX {
  interface IntrinsicElements {
    "ef-badge": {
      color?: ColorSet = 'primary';
      count?: number;
      efId?: string;
      icon?: IconName | null = null;
      shape?: ShapeSet = 'rounded';
      size?: 'sm' | 'md' | 'lg' = 'md';
      status?: StatusSet;
      statusMessage?: string;
      theme?: 'light' | 'dark' | 'forge' | 'dim' | 'high-contrast';
      variant?: 'solid' | 'subtle' | 'outline' = 'solid';
    };
    "ef-button": {
      color?: ColorSet = 'primary';
      disabled?: boolean;
      efId?: string;
      icon?: IconName | null = null;
      iconPosition?: 'start' | 'end' = 'start';
      loader?: boolean;
      loading?: boolean;
      loadingIcon?: LoadingIconName = 'loader-2';
      shape?: ShapeSet = 'rounded';
      status?: StatusSet;
      statusMessage?: string;
      theme?: 'light' | 'dark' | 'forge' | 'dim' | 'high-contrast';
      toggle?: boolean;
      toggled?: boolean = false;
      toggleIcon?: IconName | null = null;
      type?: HTMLButtonElement['type'] = 'button';
      variant?: 'solid' | 'ghost' | 'link' | 'outline' | 'soft' = 'solid';
    };
    "ef-icon": {
      color?: ColorSet | 'currentColor' = 'currentColor';
      efId?: string;
      height?: string;
      name?: string;
      spinner?: boolean;
      status?: StatusSet;
      statusMessage?: string;
      strokeWidth?: StrokeWidthPreset | string = '2';
      theme?: 'light' | 'dark' | 'forge' | 'dim' | 'high-contrast';
      width?: string = '2rem';
    };
    "ef-status": {
      efId?: string;
      fontSize?: string = '0.875rem';
      icon?: IconName | null;
      status?: StatusSet;
      statusMessage?: string;
      theme?: 'light' | 'dark' | 'forge' | 'dim' | 'high-contrast';
    };
  }
}

export {};
