import fs from "fs";
import path from "path";

const COMPONENT_DIR = "./src/components";
const OUTPUT = "./src/types/ef-jsx.d.ts";
const EF_ELEMENT_PATH = "./src/lib/ef-element.ts";
const baseProps = extractProps(EF_ELEMENT_PATH);

/* -------------------------------------------------------
   Utility: recursively find all .ts files
------------------------------------------------------- */
function getComponentFiles(dir) {
  return fs.readdirSync(dir).flatMap(file => {
    const full = path.join(dir, file);
    if (fs.statSync(full).isDirectory()) return getComponentFiles(full);
    if (file.endsWith(".ts")) return [full];
    return [];
  });
}

/* -------------------------------------------------------
   Extract Lit @property definitions
------------------------------------------------------- */
function extractProps(file) {
  const source = fs.readFileSync(file, "utf8");
  const props = {};

  // Normalize whitespace to make regex more reliable
  const clean = source.replace(/\s+/g, " ");

  /* -------------------------------------------------------
     1) @property(...) foo: type;
  ------------------------------------------------------- */
  const typedRegex =
    /@property\s*\([^)]*\)\s*(public\s+|private\s+|protected\s+)?(?<name>[a-zA-Z0-9_]+)\??!?\s*:\s*(?<type>[^;\n]+)/g;


  let match;
  while ((match = typedRegex.exec(clean))) {
    props[match.groups.name] = match.groups.type.trim();
  }

  /* -------------------------------------------------------
     2) @property({ type: X }) foo;
        → infer type from decorator
  ------------------------------------------------------- */
  const decoratorTypeRegex =
    /@property\s*\(\s*\{\s*type\s*:\s*(?<litType>Boolean|String|Number)\s*}\s*\)\s*(public\s+|private\s+|protected\s+)?(?<name>[a-zA-Z0-9_]+)\s*[=;]/g;

  while ((match = decoratorTypeRegex.exec(clean))) {
    const litType = match.groups.litType;
    const tsType =
      litType === "Boolean"
        ? "boolean"
        : litType === "Number"
        ? "number"
        : "string";

    props[match.groups.name] = tsType;
  }

  /* -------------------------------------------------------
     3) @property() foo = value;
        → infer type from initializer
  ------------------------------------------------------- */
  const inferredRegex =
    /@property\s*\([^)]*\)\s*(public\s+|private\s+|protected\s+)?(?<name>[a-zA-Z0-9_]+)\s*=\s*(?<value>true|false|[0-9]+|"[^"]*"|'[^']*')/g;

  while ((match = inferredRegex.exec(clean))) {
    const value = match.groups.value;

    let tsType = "string";
    if (value === "true" || value === "false") tsType = "boolean";
    else if (!isNaN(Number(value))) tsType = "number";

    props[match.groups.name] = tsType;
  }

  /* -------------------------------------------------------
     4) @property() foo;
        → no type, no initializer → default to string
  ------------------------------------------------------- */
  const bareRegex =
    /@property\s*\([^)]*\)\s*(public\s+|private\s+|protected\s+)?(?<name>[a-zA-Z0-9_]+)\s*;/g;

  while ((match = bareRegex.exec(clean))) {
    if (!props[match.groups.name]) {
      props[match.groups.name] = "string";
    }
  }

  /* -------------------------------------------------------
    5) @property() get/set name()
  ------------------------------------------------------- */
  const accessorRegex =
    /@property\s*\([^)]*\)\s*(public\s+|private\s+|protected\s+)?(?:get|set)\s+(?<name>[a-zA-Z0-9_]+)\s*\(/g;

  while ((match = accessorRegex.exec(clean))) {
    const name = match.groups.name;

    // If type wasn't already inferred, default to string
    if (!props[name]) {
      props[name] = "string";
    }
  }

  return props;
}

/* -------------------------------------------------------
   Convert filename → tag name
------------------------------------------------------- */
function tagFromFilename(file) {
  return path.basename(file).replace(".ts", "");
}

/* -------------------------------------------------------
   Build JSX namespace entries
------------------------------------------------------- */
function generate() {
  const files = getComponentFiles(COMPONENT_DIR);

  const entries = [];

  for (const file of files) {
    const tag = tagFromFilename(file);

    if (!tag.startsWith("ef-")) continue;

    const componentProps = extractProps(file);

    // merge inherited props
    const props = { ...baseProps, ...componentProps };

    const propLines = Object.entries(props)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([name, type]) => `      ${name}?: ${type};`)
      .join("\n");

    entries.push({
      tag,
      block: `    "${tag}": {\n${propLines}\n    };`
    });
  }

  const fileContent = `// AUTO-GENERATED FILE -- DO NOT EDIT
// Generated by scripts/generate-jsx.js

declare namespace JSX {
  interface IntrinsicElements {
${entries.map(e => e.block).join("\n")}
  }
}

export {};
`;

  fs.writeFileSync(OUTPUT, fileContent);
  console.log("Generated:", OUTPUT);
}

generate();