import fs from 'fs';
import path from 'path';

const outlineDir = './node_modules/@tabler/icons/icons/outline';
const filledDir = './node_modules/@tabler/icons/icons/filled';
const logosDir = './src/assets/logos'

const iconsOut = './src/assets/icons/icons.ts';
const typesOut = './src/assets/icons/icon-types.ts';

function loadIcons(dir, suffix = '') {
  return fs
    .readdirSync(dir)
    .filter(f => f.endsWith('.svg'))
    .map(file => {
      const name = file.replace('.svg', '').replace('icon-', '') + suffix;
      const svgContent = fs.readFileSync(path.join(dir, file), 'utf8');
      return { name, svg: svgContent };
    });
}


const logoIcons = loadIcons(logosDir);
const outlineIcons = loadIcons(outlineDir);
const filledIcons = loadIcons(filledDir, '-filled');
const allIcons = [...logoIcons, ...outlineIcons, ...filledIcons];

/* -------------------------------------------------------
   1) Generate icons.ts
------------------------------------------------------- */

let iconsFile = `import { svg, type TemplateResult } from 'lit';

export type IconsType = { [key: string]: TemplateResult<2> };

export const icons: IconsType = {
`;

for (const icon of allIcons) {
  iconsFile += `  "${icon.name}": svg\`${icon.svg}\`,\n`;
}

iconsFile += `};
`;

fs.writeFileSync(iconsOut, iconsFile);


/* -------------------------------------------------------
   2) Generate icon-types.ts (runtime array + union type)
------------------------------------------------------- */

const iconNamesArray = allIcons.map(i => `  "${i.name}",`).join('\n');

const typesFile = `// AUTO-GENERATED FILE -- DO NOT EDIT
// Generated by scripts/generate-icons.js

export const iconNames = [
${iconNamesArray}
] as const;

export type IconName = typeof iconNames[number];
`;

fs.writeFileSync(typesOut, typesFile);

console.log('Generated icons.ts and icon-types.ts');